// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQLEB6ERLeccSx1f29UOiQlwYzDoOxtU',
    appId: '1:462293336244:web:111a71bf482b88633257e1',
    messagingSenderId: '462293336244',
    projectId: 'laboratorios-6e795',
    authDomain: 'laboratorios-6e795.firebaseapp.com',
    storageBucket: 'laboratorios-6e795.firebasestorage.app',
    measurementId: 'G-5HTH53PYJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMkRYxL1DEUworuSPCwnlb8gMt3h27Lo',
    appId: '1:462293336244:android:7471f9d7258c33d23257e1',
    messagingSenderId: '462293336244',
    projectId: 'laboratorios-6e795',
    storageBucket: 'laboratorios-6e795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTJFT5wSWIWyhjcG_5UDIMDvr6qRG7f4M',
    appId: '1:462293336244:ios:6b1b681d76378cb33257e1',
    messagingSenderId: '462293336244',
    projectId: 'laboratorios-6e795',
    storageBucket: 'laboratorios-6e795.firebasestorage.app',
    iosBundleId: 'com.example.inventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTJFT5wSWIWyhjcG_5UDIMDvr6qRG7f4M',
    appId: '1:462293336244:ios:6b1b681d76378cb33257e1',
    messagingSenderId: '462293336244',
    projectId: 'laboratorios-6e795',
    storageBucket: 'laboratorios-6e795.firebasestorage.app',
    iosBundleId: 'com.example.inventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGQLEB6ERLeccSx1f29UOiQlwYzDoOxtU',
    appId: '1:462293336244:web:2b1e9277a5ceb90b3257e1',
    messagingSenderId: '462293336244',
    projectId: 'laboratorios-6e795',
    authDomain: 'laboratorios-6e795.firebaseapp.com',
    storageBucket: 'laboratorios-6e795.firebasestorage.app',
    measurementId: 'G-8GQS6EVHPT',
  );
}
